[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "matplotlib>=3.9.4",
    "notebook>=7.4.5",
    "openbb>=4.1.3",
    "pyside6>=6.9.2",
    "seaborn>=0.13.2",
]
